version: '3'
services:
  api:
    image: ${DTR_SAMPLE_APP_REPO}/py-apigateway:latest
    ports:
      - "5001:5000"
    container_name: j-api-gateway
    entrypoint: ["opentelemetry-instrument",  "python", "app.py"]
    env_file:
      - setup.env
    logging:
      driver: none

  bookings:
    image: ${DTR_SAMPLE_APP_REPO}/py-bookings:latest
    container_name: j-bookings
    entrypoint: ["opentelemetry-instrument",  "python", "app.py"]
    env_file:
      - setup.env
    logging:
      driver: none

  payments:
    image: ${DTR_SAMPLE_APP_REPO}/py-payments:latest
    container_name: j-payments
    entrypoint: ["opentelemetry-instrument",  "python", "app.py"]
    env_file:
      - setup.env
    logging:
      driver: none

  reservations:
    image: ${DTR_SAMPLE_APP_REPO}/py-reservations:latest
    container_name: j-reservations
    entrypoint: ["opentelemetry-instrument",  "python", "app.py"]
    env_file:
      - setup.env
    logging:
      driver: none

  jaeger:
      container_name: jaeger
      image: jaegertracing/all-in-one
      ports:
          - 5775:5775/udp
          - 6831:6831/udp
          - 6832:6832/udp
          - 5778:5778
          - 16686:16686
          - 14268:14268
          - 9411:9411


