version: '3'
services:
  api:
    build:
        context: ../../bookapi
    ports:
      - "5001:5000"
    environment:
        BOOK_SVC: http://appd_book_1:5000/booking
        JAEGER_HOST: appd_jaeger_1
        APPD_APP_NAME: booking
        APPD_TIER_NAME: api
        APPD_NODE_NAME: 0
    env_file:
      - appd.env
    entrypoint: ["pyagent", "run", "--",  "python", "app.py"]
  book:
    build:
        context: ../../booksvc
    environment:
        PAY_SVC: http://appd_payment_1:5000/process
        RSV_SVC: http://appd_reserve_1:5000/reserve
        JAEGER_HOST: appd_jaeger_1
        APPD_TIER_NAME: book
    entrypoint: ["pyagent", "run", "--",  "python", "app.py"]
    env_file:
      - appd.env
  payment:
    build:
        context: ../../paymentsvc
    entrypoint: ["pyagent", "run", "--",  "python", "app.py"]
    environment:
        JAEGER_HOST: appd_jaeger_1
        APPD_TIER_NAME: payment
    env_file:
      - appd.env
  reserve:
    build:
        context: ../../rsvsvc
    entrypoint: ["pyagent", "run", "--",  "python", "app.py"]
    environment:
        JAEGER_HOST: appd_jaeger_1
        APPD_TIER_NAME: reserve
    env_file:
      - appd.env
  jaeger:
      image: jaegertracing/all-in-one
      ports:
          - 5775:5775/udp
          - 6831:6831/udp
          - 6832:6832/udp
          - 5778:5778
          - 16686:16686
          - 14268:14268
          - 9411:9411


