version: '3'
services:
  api:
    build:
        context: ../../bookapi
    ports:
      - "5001:5000"
    environment:
        BOOK_SVC: http://ot_book_1:5000/booking
        JAEGER_HOST: ot_jaeger_1
        APPDYNAMICS_AGENT_APPLICATION_NAME: booking
        APPDYNAMICS_AGENT_TIER_NAME: api
        APPDYNAMICS_AGENT_NODE_NAME: 0
    entrypoint: ["pyagent", "python", "app.py"]
  book:
    build:
        context: ../../booksvc
    environment:
        PAY_SVC: http://ot_payment_1:5000/process
        RSV_SVC: http://ot_reserve_1:5000/reserve
        JAEGER_HOST: ot_jaeger_1
        APPDYNAMICS_AGENT_APPLICATION_NAME: booking
        APPDYNAMICS_AGENT_TIER_NAME: book
        APPDYNAMICS_AGENT_NODE_NAME: 0
    entrypoint: ["pyagent", "python", "app.py"]
  payment:
    build:
        context: ../../paymentsvc
    entrypoint: ["pyagent", "python", "app.py"]
    environment:
        JAEGER_HOST: ot_jaeger_1
        APPDYNAMICS_AGENT_APPLICATION_NAME: booking
        APPDYNAMICS_AGENT_TIER_NAME: payment
        APPDYNAMICS_AGENT_NODE_NAME: 0
  reserve:
    build:
        context: ../../rsvsvc
    entrypoint: ["pyagent", "python", "app.py"]
    environment:
        JAEGER_HOST: ot_jaeger_1
        APPDYNAMICS_AGENT_APPLICATION_NAME: booking
        APPDYNAMICS_AGENT_TIER_NAME: reserve
        APPDYNAMICS_AGENT_NODE_NAME: 0
  jaeger:
      image: jaegertracing/all-in-one
      ports:
          - 5775:5775/udp
          - 6831:6831/udp
          - 6832:6832/udp
          - 5778:5778
          - 16686:16686
          - 14268:14268
          - 9411:9411


