version: '3'
services:
  api:
    build:
        context: ../../bookapi
    ports:
      - "5001:5000"
    container_name: api
    environment:
        APPD_TIER_NAME: api
    env_file:
      - appd.env
      - setup.env
    entrypoint: ["pyagent", "run", "--",  "python", "app.py"]

  bookings:
    build:
        context: ../../booksvc
    container_name: bookings
    environment:
        APPD_TIER_NAME: booking
    entrypoint: ["pyagent", "run", "--",  "python", "app.py"]
    env_file:
      - appd.env
      - setup.env

  payments:
    build:
        context: ../../paymentsvc
    container_name: payments
    environment:
        APPD_TIER_NAME: payment
    env_file:
      - appd.env
      - setup.env
    entrypoint: ["pyagent", "run", "--",  "python", "app.py"]

  reservations:
    container_name: reservations
    build:
        context: ../../rsvsvc
    environment:
        JAEGER_HOST: jaeger
    env_file:
      - appd.env
      - setup.env
    entrypoint: ["pyagent", "run", "--",  "python", "app.py"]

  jaeger:
      container_name: jaeger
      image: jaegertracing/all-in-one
      ports:
          - 5775:5775/udp
          - 6831:6831/udp
          - 6832:6832/udp
          - 5778:5778
          - 16686:16686
          - 14268:14268
          - 9411:9411


