receivers:
  # otlp:
  #   protocols:
  #     grpc:
  redis:
    endpoint: 0.0.0.0:6379
    service_name: "my-test-redis"
    collection_interval: 30s
  
  hostmetrics:
    collection_interval: 10s
    scrapers:
      cpu:
      memory:
      disk:
      network:

exporters:
  otlp:
    endpoint: 0.0.0.0:5000
    insecure: true
    headers: {"x-appd-key": "efgh"}

  prometheus:
    endpoint: 0.0.0.0:8889
    namespace: promexample
    const_labels:
      label1: value1
  
  logging:
    loglevel: info

service:
  pipelines:
    metrics:
      receivers: [hostmetrics,redis]
      exporters: [logging,otlp]
