processors:
  resource:
    attributes:
    - key: cloud.zone
      value: "zone-1"
      action: upsert
    - key: host.id
      value: "123"
      action: upsert
    - key: host.name
      action: upsert
      value: "host_machine_123"

receivers:
  redis:
    endpoint: 0.0.0.0:6379
    service_name: "my-test-redis"
    collection_interval: 30s
  
  hostmetrics:
    scrapers:
      cpu:
      memory:

exporters:
  otlp:
    endpoint: 0.0.0.0:5000
    insecure: true
    headers: {"x-appd-key": "efgh"}

  prometheus:
    endpoint: 0.0.0.0:8889
    namespace: promexample
    const_labels:
      label1: value1
  
  logging:
    loglevel: info

service:
  pipelines:
    metrics:
      receivers: [hostmetrics]
      processors: [resource]
      exporters: [logging,otlp]
