version: '3'
services:
  api:
    image: ${DTR_SAMPLE_APP_REPO}/py-apigateway:${TAG}
    build:
        context: bookapi
        
  py-payments:
    image: ${DTR_SAMPLE_APP_REPO}/py-payments:${TAG}
    build:
        context: paymentsvc

  reservations:
    image: ${DTR_SAMPLE_APP_REPO}/py-reservations:${TAG}
    build:
        context: rsvsvc

  ingest:
    image: ${DTR_SAMPLE_APP_REPO}/mock-traces-ingest:${TAG}
    build:
      context: ingest

