version: '3'
services:
  api:
    image: ${DTR_SAMPLE_APP_REPO}/py-apigateway
    build:
      context: bookapi
    ports:
      - "5001:5000"
    container_name: py-api-gateway
    entrypoint: ["opentelemetry-instrument", "python", "app.py"]
    env_file:
      - setup.env

  bookings:
    image: ${DTR_SAMPLE_APP_REPO}/py-bookings
    build:
      context: booksvc
    container_name: py-bookings
    entrypoint: ["opentelemetry-instrument",  "python", "app.py"]
    env_file:
      - setup.env


  payments:
    image: ${DTR_SAMPLE_APP_REPO}/py-payments
    build:
      context: paymentsvc
    container_name: py-payments
    entrypoint: ["opentelemetry-instrument",  "python", "app.py"]
    env_file:
      - setup.env

  reservations:
    image: ${DTR_SAMPLE_APP_REPO}/py-reservations
    build:
      context: rsvsvc
    container_name: py-reservations
    entrypoint: ["opentelemetry-instrument",  "python", "app.py"]
    env_file:
      - setup.env


  # Collector
  otel-collector:
    #image: otel/opentelemetry-collector-dev
    image: dtr.corp.appdynamics.com/pavan.krishna/otelcol:dev
    container_name: otel-collector
    command: ["--config=/etc/otel-config.yml", "${OTELCOL_ARGS}"]
    volumes:
      - ./otel-config.yml:/etc/otel-config.yml
    ports:
      - 55678:55678       # receiving port
      - 55680
    env_file:
      - setup.env

  grpc-ingest:
    image: ${DTR_SAMPLE_APP_REPO}/mock-traces-ingest
    build:
      context: ingest
    container_name: grpc-ingest
    entrypoint: ["./serve_grpc"]
    env_file:
      - setup.env



  
