receivers:
  otlp:
    protocols:
      grpc:

exporters:
  otlp:
    endpoint: grpc-ingest:5000
    insecure: true
    headers: {"x-appd-key": "efgh"}

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [otlp]
