receivers:
  otlp:
    protocols:
      grpc:

exporters:
  otlp:
    http:
      endpoint: http://http-ingest:5000
      format: json 
      insecure: true
      headers: {"appd-x-key": "abcd"}

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [otlp]
    metrics:
      receivers: [otlp]
      exporters: [otlp]