receivers:
  otlp:

exporters:
  jaeger:
    endpoint: jaeger:14250
    insecure: true

  zipkin:
    endpoint: "http://zipkin:9411/api/v2/spans"
    format: proto

service:
  pipelines:
    traces:
      receivers: [otlp]
      #exporters: [zipkin, jaeger]
      exporters: [zipkin] # just zipkin for now - jaeger has a bug importing traces from OT Collector see https://github.com/jaegertracing/jaeger/issues/2300
