version: '3'
services:
  api:
    build:
        context: ../../bookapi
    ports:
      - "5001:5000"
    container_name: api
    entrypoint: ["opentelemetry-instrument",  "python", "app.py","--exporter", "otc"]
    env_file:
      - setup.env

  bookings:
    build:
        context: ../../booksvc
    container_name: bookings
    entrypoint: ["opentelemetry-instrument",  "python", "app.py","--exporter", "otc"]
    env_file:
      - setup.env

  payments:
    build:
        context: ../../paymentsvc
    container_name: payments
    entrypoint: ["opentelemetry-instrument",  "python", "app.py" ,"--exporter", "otc"]
    env_file:
      - setup.env

  reservations:
    container_name: reservations
    build:
        context: ../../rsvsvc
    entrypoint: ["opentelemetry-instrument",  "python", "app.py", "--exporter", "otc"]
    env_file:
      - setup.env

  # Collector
  otel-collector:
    image: otel/opentelemetry-collector:0.4.0
    container_name: otel-collector
    command: ["--config=/etc/otel-config.yml"]
    volumes:
      - ./otel-config.yml:/etc/otel-config.yml
    ports:
      - "55678:55678"      # receiving port
      - "55680:55680"
    env_file:
      - setup.env

  ingest:
    build:
        context: ../../ingest
    container_name: ingest
    entrypoint: [ "python", "app.py"]
    env_file:
      - setup.env