version: '3'
services:
  # Collector
  otel-collector:
    image: ${DTR_OT_REPO}/otelcontribcol:latest
    container_name: otel-collector
    command: ["--config=/etc/otel-config.yml", "${OTELCOL_ARGS}"]
    volumes:
      - ./otel-config.yml:/etc/otel-config.yml
    ports:
      - 55678:55678       # receiving port
      - 55680
    depends_on:
      - mock-cms
    env_file:
      - setup.env
    logging:
      driver: none

  mock-cms:
    image: ${DTR_SAMPLE_APP_REPO}/mock-cms:${TAG}
    container_name: mock-cms
    entrypoint: [ "python", "app.py"]
    env_file:
      - setup.env
    ports:
      - "5000:5000"




