---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookings-deploy
  labels:
    app: bookings
spec:
  selector:
    matchLabels:
      app: bookings
  template:
    spec:
      containers:
        - name: bookings-container
          image: dtr.corp.appdynamics.com/pavan.krishna/py-bookings:latest
          ports:
            - containerPort: 5000
          command: ["opentelemetry-instrument", "python", "app.py"]
          env:
            - name: OTC_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: CONTAINER_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: "container.id=$(CONTAINER_NAME)"
            - name: OTC_PORT
              value: "55680"
            - name: PAY_SVC
              value: http://payments-svc:5000/process
            - name: RSV_SVC
              value: http://reservations-svc:5000/reserve
            - name: BOOK_SVC
              value: http://bookings-svc:5000/booking
    metadata:
      labels:
        app: bookings
  replicas: 1
  minReadySeconds: 10
  strategy:
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1

---
apiVersion: v1
kind: Service
metadata:
  name: bookings-svc
  labels:
    app: bookings
spec:
  type: ClusterIP
  ports:
    - port: 5000
      protocol: TCP
  selector:
    app: bookings



