---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-deploy
  labels:
    app: gateway
spec:
  selector:
    matchLabels:
      app: gateway
  template:
    spec:
      containers:
        - name: gateway-container
          image: dtr.corp.appdynamics.com/pavan.krishna/py-apigateway:latest
          ports:
            - containerPort: 5000
          command: ["opentelemetry-instrument", "python", "app.py"]
          env:
            - name: OTC_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: OTC_PORT
              value: "55680"
            - name: PAY_SVC
              value: http://payments-svc:5000/process
            - name: RSV_SVC
              value: http://reservations-svc:5000/reserve
            - name: BOOK_SVC
              value: http://bookings-svc:5000/booking
    metadata:
      labels:
        app: gateway
  replicas: 1
  minReadySeconds: 10
  strategy:
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1

---
apiVersion: v1
kind: Service
metadata:
  name: gateway-svc
  labels:
    app: gateway
spec:
  type: NodePort
  ports:
    - port: 5000
      nodePort: 30001
      protocol: TCP
  selector:
    app: gateway



