version: '3'
services:
  api:
    build:
        context: ../../bookapi
    ports:
      - "5001:5000"
    container_name: api
    entrypoint: ["opentelemetry-instrument",  "python", "app.py"]
    env_file:
      - setup.env

  bookings:
    build:
        context: ../../booksvc
    container_name: bookings
    entrypoint: ["opentelemetry-instrument",  "python", "app.py"]
    env_file:
      - setup.env

  payments:
    build:
        context: ../../paymentsvc
    container_name: payments
    entrypoint: ["opentelemetry-instrument",  "python", "app.py"]
    env_file:
      - setup.env

  reservations:
    container_name: reservations
    build:
        context: ../../rsvsvc
    entrypoint: ["opentelemetry-instrument",  "python", "app.py"]
    env_file:
      - setup.env

  jaeger:
      container_name: jaeger
      image: jaegertracing/all-in-one
      ports:
          - 5775:5775/udp
          - 6831:6831/udp
          - 6832:6832/udp
          - 5778:5778
          - 16686:16686
          - 14268:14268
          - 9411:9411


