processors:
  resource:
    type: "host"
    labels: {
      "cloud.zone": "zone-1",
      "k8s.cluster.name": "k8s-cluster",
      "host.name": "k8s-node",
    }

receivers:
  otlp:
    protocols:
      grpc:
  hostmetrics:
    collection_interval: 10s
    scrapers:
      process:
        include:
          match_type: "docker*"

exporters:
  appdynamics:
    traces:
      grpc:
        endpoint: mock-traces-ingest:5000
        insecure: true
    metrics:
      http:
        endpoint: mock-cms:5000
    account: customer1
    access_key: key

  jaeger:
    endpoint: jaeger:14250
    insecure: true

  zipkin:
    endpoint: "http://zipkin:9411/api/v2/spans"
    format: proto

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [resource]
      exporters: [appdynamics,zipkin]
    metrics:
      receivers: [hostmetrics]
      processors: [resource]
      exporters: [appdynamics]