processors:
  resource:
    attributes:
    - key: cloud.zone
      value: "zone-1"
      action: upsert
    - key: host.name
      value: "sample-container"
      action: upsert
    - key: appdynamics.application
      action: upsert
      value: "ticket-hub"
    - key: appdynamics.service
      from_attribute: service.name
      action: upsert

receivers:
  otlp:
    protocols:
      grpc:

exporters:
  otlp:
    endpoint: ingest:5000
    insecure: true

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [resource]
      exporters: [otlp]
