processors:
  resource:
    type: "host"
    labels: {
      "cloud.zone": "zone-1",
      "k8s.cluster.name": "k8s-cluster",
      "host.name": "k8s-node",
      "appdynamics.application": "ticket-hub"
    }

receivers:
  otlp:
    protocols:
      grpc:

exporters:
  appdynamics:
    traces:
      grpc:
        endpoint: mock-traces-ingest:5000
        insecure: true
  zipkin:
    endpoint: "http://zipkin:9411/api/v2/spans"
    format: proto

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [resource]
      exporters: [appdynamics,zipkin]
