receivers:
  otlp:
    protocols:
      grpc:
  hostmetrics:
    collection_interval: 30s
    scrapers:
      cpu:
      memory:

exporters:
  otlp:
    endpoint: ingest:5000
    insecure: true


service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [otlp]
    metrics:
      receivers: [hostmetrics]
      exporters: [otlp]