processors:
  resource:
    attributes:
    - key: cloud.zone
      value: "zone-1"
      action: upsert
    - key: host.name
      value: "sample-container"
      action: upsert
    - key: appdynamics.application
      action: upsert
      value: "ticket-hub"
    - key: appdynamics.service
      from_attribute: service.name
      action: upsert

receivers:
  otlp:
    protocols:
      grpc:

exporters:
  appdynamics:
    traces:
      grpc:
        endpoint: otis-mock-injest:80
        insecure: true
  zipkin:
    endpoint: "http://zipkin:9411/api/v2/spans"
    format: proto

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [resource]
      exporters: [appdynamics,zipkin]
